# Generated by Django 2.2.4 on 2019-10-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190923_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='post/'),
        ),
    ]
